### ISSUE TITLE
Exception raised during installation: Invalid requirement, parse error at "'; extra '"

### ISSUE THREAD

**Issue by Samahu** [udacity/RoboND-Python-StarterKit#5]
Getting the following exception when executing "conda env create -f environment.yml"

I am running on a new Windows 10 machine (all updates applied). I was able to reproduce the issue on a VM running Windows 10 too.

I ran into the issue using miniconda version 3.5.4 and also 3.5.11, which comes with pip 10.0.1.

```shell
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.7.0->socketIO-client->-r D:\udacity\RoboND-Python-StarterKitCopy\condaenv.iwlwx_jb.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl

Exception:
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2869, in _dep_map
    return self.__dep_map
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2663, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\packaging\requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pyparsing.py", line 1632, in parseString
    raise exc
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pyparsing.py", line 3183, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 33), (line:1, col:34)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2949, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\packaging\requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'; extra '"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_internal\basecommand.py", line 141, in main
    status = self.run(options, args)
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_internal\commands\install.py", line 330, in run
    self._warn_about_conflicts(to_install)
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_internal\commands\install.py", line 456, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_internal\operations\check.py", line 98, in check_install_conflicts
    package_set = create_package_set_from_installed()
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_internal\operations\check.py", line 41, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2607, in requires
    dm = self._dep_map
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2871, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2881, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2942, in parse_requirements
    yield Requirement(line)
  File "C:\Users\user\Miniconda3\envs\RoboNDCopy\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2951, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Invalid requirement, parse error at "'; extra '"

CondaValueError: pip returned an error


(base) D:\udacity\RoboND-Python-StarterKitCopy>
```

After this the RoboND environment is created, however, when I try to run notebook I get errors that tensorflow is not found.

**Comment by Samahu** [comment]
**Possible workaround**

I have found this to be a working solution for me:
------------------------------------------------------

After you get the failure message, activate the incomplete environment:
`(base)> activate RoboND`

Within the RoboND env run the following command:
`(RoboND)> conda update --all`

Then individually install tensorflow using pip:
`(RoboND)> pip install tensorflow==1.2.1`

Then jupyter notebook should work as expected.

**Comment by akhilesh-k** [comment]
Same with me! Installing TF separately works!
